package com.example.quanlynhansu.ui.screens

object Routes {
    const val LOGIN_SCREEN = "LOGIN_SCREEN"
    const val REGISTER_SCREEN = "REGISTER_SCREEN"

    const val HOME_SCREEN = "HOME_SCREEN"

    const val CHECK_IN_OUT_SCREEN = "CHECK_IN_OUT_SCREEN"
    const val CHECK_IN_OUT_HISTORY_SCREEN = "CHECK_IN_OUT_HISTORY_SCREEN"
    const val REPORT_CHECK_IN_OUT_SCREEN = "REPORT_CHECK_IN_OUT_SCREEN"
    // admin
    const val CHECK_IN_OUT_LIST_SCREEN = "CHECK_IN_OUT_LIST_SCREEN"
    const val REQUEST_CHECK_IN_OUT_LIST_SCREEN = "REQUEST_CHECK_IN_OUT_LIST_SCREEN"
    const val STATISTICAL_CHECK_IN_OUT_SCREEN = "STATISTICAL_CHECK_IN_OUT_SCREEN"

    const val SALARY_SCREEN = "SALARY_SCREEN"
    const val MY_SALARY_SCREEN = "MY_SALARY_SCREEN"
    // admin
    const val SALARY_LIST_SCREEN = "SALARY_LIST_SCREEN"

    const val TASK_SCREEN = "TASK_SCREEN"
    const val TASK_LIST_SCREEN = "TASK_LIST_SCREEN"
    const val REPORT_TASK_SCREEN = "REPORT_TASK_SCREEN"
    // admin
    const val ASSIGN_TASK_SCREEN = "ASSIGN_TASK_SCREEN"
    const val TASK_SCHEDULE_SCREEN = "TASK_SCHEDULE_SCREEN"
    const val REQUEST_TASK_SCREEN = "REQUEST_TASK_SCREEN"
    const val STATISTICAL_TASK_SCREEN = "STATISTICAL_TASK_SCREEN"

    const val INFO_SCREEN = "INFO_SCREEN"
    const val PROFILE_SCREEN = "PROFILE_SCREEN"
    const val UPDATE_PROFILE_SCREEN = "UPDATE_PROFILE_SCREEN"
    const val CHANGE_PASSWORD_SCREEN = "CHANGE_PASSWORD_SCREEN"

    // admin
    const val EMPLOYEE_PROFILE_SCREEN = "EMPLOYEE_PROFILE_SCREEN"
    const val UPDATE_EMPLOYEE_PROFILE_SCREEN = "UPDATE_EMPLOYEE_PROFILE_SCREEN"
    const val LOOKUP_EMPLOYEE_PROFILE_SCREEN = "LOOKUP_EMPLOYEE_PROFILE_SCREEN"
    const val STATISTICAL_EMPLOYEE_SCREEN = "STATISTICAL_EMPLOYEE_SCREEN"
    const val CHANGE_USER_ACCOUNT_SCREEN = "CHANGE_USER_ACCOUNT_SCREEN"

    const val USER_ID = "USER_ID"
    const val FULL_NAME = "FULL_NAME"
    const val POSITION = "POSITION"
    const val ROLE = "ROLE"
}